### ISSUE TITLE
[Block]: Need the API to be hosted

### ISSUE THREAD

**Issue by Anuragtech02** [Anuragtech02/kibana-mini#5]
Hey @vedangj044 
Could you please host the API somewhere? You may use [Render](https://render.com) or [Railway](https://railway.app)
This is actually blocking this #4 

This will help us test it on the deployed [link](https://kibana-mini.netlify.app/) as well

Drop the deployed link here once done
We may also need to separate the backend repository for that

**Comment by vedangj044** [comment]
The API has been hosted. Thanks for suggesting render. 
Here's the URL to the docs: https://kibana-mini-backend.onrender.com/docs
